#ifndef PERSISTENT_FEATURES_H
#define PERSISTENT_FEATURES_H

#define GPIOTE_ENABLED 1
#define NRFX_GPIOTE_ENABLED 1
#define NRFX_GPIOTE_CONFIG_IRQ_PRIORITY 6
#define NRFX_GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 4

#define NRFX_CLOCK_ENABLED 1
#define NRFX_CLOCK_CONFIG_IRQ_PRIORITY 6
#define NRFX_CLOCK_CONFIG_LF_SRC 1

#define APP_TIMER_ENABLED 1
#define APP_TIMER_SAFE_WINDOW_MS 300000
#define APP_TIMER_CONFIG_IRQ_PRIORITY 6

#define PWM_ENABLED 1
#define PWM0_ENABLED 1
#define PWM1_ENABLED 1

#define NRFX_PWM_ENABLED 1
#define NRFX_PWM0_ENABLED 1
#define NRFX_PWM1_ENABLED 1

 #define NRFX_NVMC_ENABLED 1

#endif // PERSISTENT_FEATURES_H
