#ifndef DEFINES_H
#define DEFINES_H

#define DEVICE_ID 6593

#define LED_NUMBER 4
#define LED1 NRF_GPIO_PIN_MAP(0, 6)
#define LED2_R NRF_GPIO_PIN_MAP(0, 8)
#define LED2_G NRF_GPIO_PIN_MAP(1, 9)
#define LED2_B NRF_GPIO_PIN_MAP(0, 12)

#define BLINK_TIME_SLOW_MS 1000
#define BLINK_TIME_FAST_MS 200
#define DUTY_CYCLE_DELTA 100
#define DUTY_SEQUENCE_LENGTH ((1000 / DUTY_CYCLE_DELTA) + 1)
#define REPEATS_SLOW  (BLINK_TIME_SLOW_MS / DUTY_SEQUENCE_LENGTH)
#define REPEATS_FAST  (BLINK_TIME_FAST_MS / DUTY_SEQUENCE_LENGTH)

#define DEFAULT_HUE (DEVICE_ID % 100) * 360 / 100
#define DEFAULT_SATURATION 100
#define DEFAULT_VALUE 100

#define SW1 NRF_GPIO_PIN_MAP(1, 6)
#define SW1_PRESSED 0
#define SW1_RELEASED !SW1_PRESSED
#define DEBOUNCE_MS 50
#define DOUBLE_CLICK_MS 500
#define HOLD_MS 700
#define COLOR_UPDATE_MS 50

#define MAX_COLOR_NAME_SIZE 12
#define HSV_COLOR_SIZE (4 + MAX_COLOR_NAME_SIZE)
#define MAX_COLORS 10
#define PALETTE_SIZE ((HSV_COLOR_SIZE * MAX_COLORS) + 2)

#define FLASH_PAGE_ADDR 0x0007F000
#define FLASH_SAVE_CURRENT_ADDR FLASH_PAGE_ADDR
#define FLASH_SAVE_PALETTE_ADDR (FLASH_SAVE_CURRENT_ADDR + HSV_COLOR_SIZE)

#endif